### ISSUE TITLE
Remove Geocoding API task

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk-workshop#10]
I already suggested breaking out that task into multiple, but I'd suggest removing the Geocoding task completely as it requires a dev to go out and get a key before using the API. That's not terribly difficult, but it *is* a process and it's a hassle a dev doesn't want to worry about when learning OpenWhisk.

**Comment by cfjedimaster** [comment]
To be clear - in my quick test it appears as if it works w/o a key, but the docs say otherwise.

**Comment by jthomas** [comment]
According to this post, API keys are not required for basic geocoding services.
http://stackoverflow.com/questions/33421122/why-does-the-api-work-without-key

I'll update the documentation to highlight this.
