### ISSUE TITLE
NodeJS Delay Action failing

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk-workshop#11]
The task for the delay test says this:

 Create an Action (hello-world-delay-nodejs) that returns the same message after an artificial delay of one second.

This to me means it should take, AT LEAST, 1000ms, so I used this:

function main() {
	return new Promise(function(resolve,reject) {
		setTimeout(resolve({"message":"Hello World"}),1000);
	});
}

When I tried to verify, I got:

✗ OpenWhisk Action hello-world-nodejs-delay returned response within 1000ms.

Which seems to imply it wants to return in less than 1000ms. So I changed my timeout to 100, and it didn't help.

**Comment by jthomas** [comment]
The exercise verifier was using the wrong action name, fixed now!
