### ISSUE TITLE
Instructions with links are coming through in Markdown

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk-workshop#12]
For the parameters task, the help text prints this:

Request parameters are passed as an object through the first function parameter
for the runtime interface. Here's an example of using this with the NodeJS
runtime
[https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#passing-parameters-to-an-action](https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#passing-parameters-to-an-action).

Default parameters for Actions can bound using the wsk command-line utility
[https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#setting-default-parameters](https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#setting-default-parameters)

Hopefully GitHub won't replace the Markdown...

**Comment by cfjedimaster** [comment]
And shoot - they did. So... yeah, just imagine those links in their MD version. :)

**Comment by jthomas** [comment]
Do you mean the links aren't being printed in the console? What would you expect the behaviour to be here?

**Comment by cfjedimaster** [comment]
What I mean is, I saw this, and I'll try to get GitHub to not parse it:

     You can learn more about it [here](http://someurl)

In other words, it was Markdown that wasn't processed - which makes sense since it is plain text. Normally I do links like that in this format in plain text:

    You can learn more about it here: http://someurl

or

    You can learn more it here:  Foo Docs (http://.....)

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
