### ISSUE TITLE
Minor correction: Timeout in second task explanation is 2s, not 20s

### ISSUE THREAD

**Issue by k0105** [apache/incubator-openwhisk-workshop#16]
You write "The setTimeout() JavaScript function in this case waits for twenty seconds
before calling the callback function.", but your code is
```
setTimeout(function() {
             resolve({ done: true });
             }, 2000);
```
`setTimeout()` takes milliseconds, so imho it should be 2s, not twenty.

**Comment by jthomas** [comment]
Thanks for finding this. If you want to submit a PR I'll merge, otherwise I'll try to fix this in a week or so.

**Comment by k0105** [comment]
Also: Regarding "Don't forget to remote the trigger after completing the test!" in trigger feed problem text I assume you mean "remove", not "remote".
