### ISSUE TITLE
Workshop one fails due to namespace

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk-workshop#8]
I've been using wsk for a week or so now, but when I tried the first exercise I got a failure for:

OpenWhisk namespace set incorrectly

I know for a fact its setup right.

**Comment by cfjedimaster** [comment]
When I look at my config, my namespace is set to _. No idea why, but it works.

**Comment by jthomas** [comment]
I've now removed the "namespace" check test as this is incorrect with the GA API changes.
