### ISSUE TITLE
Consider breaking up the actions task

### ISSUE THREAD

**Issue by cfjedimaster** [apache/incubator-openwhisk-workshop#9]
The task for writing actions in NodeJS has you writing 3 actions, and while the first one is extremely trivial, the second and third are not. (Ok, the second *is* pretty easy too, but for a new user, it will be something they have to look up.) I really think they should be separate tasks. 

Even if they were all really easy, my gut says NodeSchool tasks should do one thing at a time.

**Comment by jthomas** [comment]
Good feedback, I agree. 

I don't have time to work on this but if you want to have a go and submit a PR I'll happily merge.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
